export const reset = {
  gridColumn: 1,
  gridRow: 1,
  justifySelf: "start",
  alignSelf: "start",
  display: "inline-block",
  fontSize: "clamp(16px, 2vw, 25px)",
  fontWeight: "bold",
  border: "2px solid black",
  padding: "0.5em 1em",
  cursor: "pointer",
  borderRadius: "6px",
};
export const rules = {
  gridColumn: 3,
  gridRow: 1,
  justifySelf: "end",
  alignSelf: "start",
  display: "flex",
  alignItems: "center",
  gap: "0.75em",
  fontSize: "clamp(16px, 2vw, 25px)",
  fontWeight: "bold",
  border: "2px solid black",
  padding: "0.5em 1em",
  cursor: "pointer",
  borderRadius: "6px",
};
